//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax_Calling_for_binding_dropdown_using_SP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int Cityid { get; set; }
        public string CityName { get; set; }
        public string Sid { get; set; }
    }
}
