//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataBindingMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AzuredbEntities : DbContext
    {
        public AzuredbEntities()
            : base("name=AzuredbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emptable> Emptables { get; set; }
    
        public virtual ObjectResult<crudeemp_Result> crudeemp(Nullable<int> id, string empname, string email, string salary, string crudOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var empnameParameter = empname != null ?
                new ObjectParameter("Empname", empname) :
                new ObjectParameter("Empname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var salaryParameter = salary != null ?
                new ObjectParameter("Salary", salary) :
                new ObjectParameter("Salary", typeof(string));
    
            var crudOptionParameter = crudOption != null ?
                new ObjectParameter("CrudOption", crudOption) :
                new ObjectParameter("CrudOption", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crudeemp_Result>("crudeemp", idParameter, empnameParameter, emailParameter, salaryParameter, crudOptionParameter);
        }
    }
}
